[build]
  command = "pnpm -r install && pnpm nx build preview"
  publish = "apps/preview/node_modules/webextension/build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF apps/webextension apps/preview"

[functions]
  directory = "apps/preview/functions"