[build]
  command = "pnpm -r install && pnpm nx build preview"
  publish = "apps/preview/node_modules/webextension/build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF apps/webextension apps/preview"

[functions]
  directory = "apps/preview/functions"

[[plugins]]
  package = "apps/preview/plugins/netlify-plugin-interpolate-env-variable"
  [plugins.inputs]
    variable = "PUBLIC_EXTERNAL_ASSETS_URI"