name: Create new release

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New version'
        required: true
        type: string

jobs:
  set-new-version:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{steps.commit_new_version.outputs.commit_hash}}
    steps:
      - uses: actions/checkout@v4

      - name: Set new version format
        run: |
          if [[ "${{ inputs.new_version }}" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; 
          then 
            echo "New version looks okay";
            MAJOR="${BASH_REMATCH[1]}"
            MINOR="${BASH_REMATCH[2]}"
            PATCH="${BASH_REMATCH[3]}"
            sed -r -i "s/\"version\": *\"[0-9]+\\.[0-9]+\\.[0-9]+\"/\"version\": \"$MAJOR.$MINOR.$PATCH\"/g" webextension/package.json
          else 
            echo "Invalid version format";
            exit 1
          fi

      - id: commit_new_version
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: "chore: Updated version"
          push_options: '--force'

  create-release:
    runs-on: ubuntu-latest
    needs: set-new-version
    outputs:
      upload_url: ${{steps.create-release.outputs.upload_url}}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{needs.set-new-version.outputs.commit_hash}}"
          fetch-depth: 0

      - id: create-release
        uses: ncipollo/release-action@v1.14.0
        with:
          bodyFile: ".github/release-body.md"
          artifactErrorsFailBuild: true
          updateOnlyUnreleased: true
          allowUpdates: true
          removeArtifacts: true
          draft: true
          tag: "v${{ inputs.new_version }}"
          commit: "${{needs.set-new-version.outputs.commit_hash}}"
  
  build:
    runs-on: ubuntu-latest
    environment: webextension
    needs: [set-new-version, create-release]

    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      PUBLIC_FLICKR_API_KEY: ${{secrets.PUBLIC_FLICKR_API_KEY}}
      PUBLIC_CORS_BYPASS: ${{secrets.PUBLIC_CORS_BYPASS}}
      PUBLIC_OWM_REDIRECT: ${{secrets.PUBLIC_OWM_REDIRECT}}
      PUBLIC_EXTERNAL_ASSETS_URI: ${{secrets.PUBLIC_EXTERNAL_ASSETS_URI}}
      PUBLIC_THEQUOTEAPI_KEY: ${{secrets.PUBLIC_THEQUOTEAPI_KEY}}
      PUBLIC_NASA_APOD_API_KEY: ${{secrets.PUBLIC_NASA_APOD_API_KEY}}
      PUBLIC_PEXELS_API_KEY: ${{secrets.PUBLIC_PEXELS_API_KEY}}
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{needs.set-new-version.outputs.commit_hash}}"
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./webextension/.nvmrc
    
      - uses: pnpm/action-setup@v3.0.0
        name: Install pnpm
        with:
          version: latest
          run_install: false

      - name: Install dependencies
        working-directory: ./webextension
        run: |
          sudo apt-get install -y rename
          pnpm install

      - name: Build
        working-directory: ./webextension
        run: |
          pnpm build
          pnpm build:web-ext:chromium
          pnpm build:web-ext:firefox
          rename 's/sveltab-/sveltab-chromium-/' build-web-ext/chromium/sveltab-*.zip
          rename 's/sveltab-/sveltab-firefox-/' build-web-ext/firefox/sveltab-*.zip
          find ./build-web-ext -type f -mindepth 2 -exec mv {} ./build-web-ext \;
      
      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            webextension/build-web-ext/**/*.zip
      
      - name: Upload Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: webextension/build-web-ext/**/*.zip

  checksum:
    runs-on: ubuntu-latest
    needs: ['create-release', 'build']
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: release
          path: release
      
      - name: Generate checksum
        run: |
          cd release
          find . -type f -maxdepth 1 -exec sha256sum {} \; > ../checksum.txt

      - name: Upload Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: checksum.txt

  publish-mozilla:
    runs-on: ubuntu-latest
    needs: ['build', 'checksum']
    environment: store-mozilla
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: release
          path: release

      - name: Get addon file path
        run: |
          cd release
          echo "ADDON_FILE=$(find $(pwd) -type f -maxdepth 1 -name 'sveltab-firefox-*.zip')" >> $GITHUB_OUTPUT
        id: find_addon_file

      - uses: wdzeng/firefox-addon@v1
        name: Publish to Mozilla Addons Store
        with:
          addon-guid: ${{ secrets.ADDON_GUID }}
          xpi-path: ${{ steps.find_addon_file.outputs.ADDON_FILE }}
          self-hosted: false
          jwt-issuer: ${{ secrets.JWT_ISSUER }}
          jwt-secret: ${{ secrets.JWT_SECRET }}

  publish-chrome-store:
    runs-on: ubuntu-latest
    needs: ['build', 'checksum']
    environment: chrome-store
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: release
          path: release

      - name: Get addon file path
        run: |
          cd release
          echo "ADDON_FILE=$(find $(pwd) -type f -maxdepth 1 -name 'sveltab-chromium-*.zip')" >> $GITHUB_OUTPUT
        id: find_addon_file

      - uses: wdzeng/chrome-extension@v1
        with:
          extension-id: your-extension-id
          zip-path: ${{ steps.find_addon_file.outputs.ADDON_FILE }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}

  publish-edge-store:
    runs-on: ubuntu-latest
    needs: ['build', 'checksum']
    environment: store-edge
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: release
          path: release

      - name: Get addon file path
        run: |
          cd release
          echo "ADDON_FILE=$(find $(pwd) -type f -maxdepth 1 -name 'sveltab-chromium-*.zip')" >> $GITHUB_OUTPUT
        id: find_addon_file

      - uses: wdzeng/edge-addon@v1
        with:
          product-id: ${{ secrets.PRODUCT_ID }}
          zip-path: ${{ steps.find_addon_file.outputs.ADDON_FILE }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          access-token-url: ${{ secrets.ACCESS_TOKEN_URL }}